
# Default values for scheduler-plugins-as-a-second-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scheduler:
  name: scheduler-plugins-scheduler
  image: quay.io/pbastide_rh/openshift-demo@sha256:7e12f7637c0c2602ce7b08babe19cac4c5f284bc5084fd0139ef5d51f012e749
  namespace: scheduler-plugins
  replicaCount: 1

controller:
  name: scheduler-plugins-controller
  image: quay.io/pbastide_rh/openshift-demo@sha256:a16959b476ddc961ae3aed218af3d7ac3479bdae9c53cb8a8cba0a877c7413ea
  namespace: scheduler-plugins
  replicaCount: 1

# LoadVariationRiskBalancing and TargetLoadPacking are not enabled by default
# as they need extra RBAC privileges on metrics.k8s.io.

plugins:
  enabled: ["Coscheduling","CapacityScheduling","NodeResourceTopologyMatch", "NodeResourcesAllocatable"]

global:  
   # queueSort is not indented under extensions 
   # as it needs to be globally enabled once. 
  queueSort: ["Coscheduling"]
  extensions: 
    preFilter: ["Coscheduling", "CapacityScheduling"] 
    filter: ["NodeResourceTopologyMatch"] 
    postFilter: ["Coscheduling", "CapacityScheduling"] 
    score: ["NodeResourceTopologyMatch", "NodeResourcesAllocatable"] 
    permit: ["Coscheduling"] 
    reserve: ["Coscheduling", "CapacityScheduling"] 
    postBind: ["Coscheduling"]
